
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JournalPosting` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model JournalPosting
 * 
 */
export type JournalPostingModel = runtime.Types.Result.DefaultSelection<Prisma.$JournalPostingPayload>

export type AggregateJournalPosting = {
  _count: JournalPostingCountAggregateOutputType | null
  _avg: JournalPostingAvgAggregateOutputType | null
  _sum: JournalPostingSumAggregateOutputType | null
  _min: JournalPostingMinAggregateOutputType | null
  _max: JournalPostingMaxAggregateOutputType | null
}

export type JournalPostingAvgAggregateOutputType = {
  id: number | null
  journal_entry_id: number | null
  account_id: number | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
}

export type JournalPostingSumAggregateOutputType = {
  id: number | null
  journal_entry_id: number | null
  account_id: number | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
}

export type JournalPostingMinAggregateOutputType = {
  id: number | null
  journal_entry_id: number | null
  account_id: number | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
}

export type JournalPostingMaxAggregateOutputType = {
  id: number | null
  journal_entry_id: number | null
  account_id: number | null
  debit: runtime.Decimal | null
  credit: runtime.Decimal | null
}

export type JournalPostingCountAggregateOutputType = {
  id: number
  journal_entry_id: number
  account_id: number
  debit: number
  credit: number
  _all: number
}


export type JournalPostingAvgAggregateInputType = {
  id?: true
  journal_entry_id?: true
  account_id?: true
  debit?: true
  credit?: true
}

export type JournalPostingSumAggregateInputType = {
  id?: true
  journal_entry_id?: true
  account_id?: true
  debit?: true
  credit?: true
}

export type JournalPostingMinAggregateInputType = {
  id?: true
  journal_entry_id?: true
  account_id?: true
  debit?: true
  credit?: true
}

export type JournalPostingMaxAggregateInputType = {
  id?: true
  journal_entry_id?: true
  account_id?: true
  debit?: true
  credit?: true
}

export type JournalPostingCountAggregateInputType = {
  id?: true
  journal_entry_id?: true
  account_id?: true
  debit?: true
  credit?: true
  _all?: true
}

export type JournalPostingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JournalPosting to aggregate.
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalPostings to fetch.
   */
  orderBy?: Prisma.JournalPostingOrderByWithRelationInput | Prisma.JournalPostingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JournalPostingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalPostings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalPostings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JournalPostings
  **/
  _count?: true | JournalPostingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: JournalPostingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: JournalPostingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JournalPostingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JournalPostingMaxAggregateInputType
}

export type GetJournalPostingAggregateType<T extends JournalPostingAggregateArgs> = {
      [P in keyof T & keyof AggregateJournalPosting]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJournalPosting[P]>
    : Prisma.GetScalarType<T[P], AggregateJournalPosting[P]>
}




export type JournalPostingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JournalPostingWhereInput
  orderBy?: Prisma.JournalPostingOrderByWithAggregationInput | Prisma.JournalPostingOrderByWithAggregationInput[]
  by: Prisma.JournalPostingScalarFieldEnum[] | Prisma.JournalPostingScalarFieldEnum
  having?: Prisma.JournalPostingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JournalPostingCountAggregateInputType | true
  _avg?: JournalPostingAvgAggregateInputType
  _sum?: JournalPostingSumAggregateInputType
  _min?: JournalPostingMinAggregateInputType
  _max?: JournalPostingMaxAggregateInputType
}

export type JournalPostingGroupByOutputType = {
  id: number
  journal_entry_id: number
  account_id: number
  debit: runtime.Decimal
  credit: runtime.Decimal
  _count: JournalPostingCountAggregateOutputType | null
  _avg: JournalPostingAvgAggregateOutputType | null
  _sum: JournalPostingSumAggregateOutputType | null
  _min: JournalPostingMinAggregateOutputType | null
  _max: JournalPostingMaxAggregateOutputType | null
}

type GetJournalPostingGroupByPayload<T extends JournalPostingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JournalPostingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JournalPostingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JournalPostingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JournalPostingGroupByOutputType[P]>
      }
    >
  >



export type JournalPostingWhereInput = {
  AND?: Prisma.JournalPostingWhereInput | Prisma.JournalPostingWhereInput[]
  OR?: Prisma.JournalPostingWhereInput[]
  NOT?: Prisma.JournalPostingWhereInput | Prisma.JournalPostingWhereInput[]
  id?: Prisma.IntFilter<"JournalPosting"> | number
  journal_entry_id?: Prisma.IntFilter<"JournalPosting"> | number
  account_id?: Prisma.IntFilter<"JournalPosting"> | number
  debit?: Prisma.DecimalFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  journal?: Prisma.XOR<Prisma.JournalEntryScalarRelationFilter, Prisma.JournalEntryWhereInput>
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
}

export type JournalPostingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  journal?: Prisma.JournalEntryOrderByWithRelationInput
  account?: Prisma.AccountOrderByWithRelationInput
}

export type JournalPostingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.JournalPostingWhereInput | Prisma.JournalPostingWhereInput[]
  OR?: Prisma.JournalPostingWhereInput[]
  NOT?: Prisma.JournalPostingWhereInput | Prisma.JournalPostingWhereInput[]
  journal_entry_id?: Prisma.IntFilter<"JournalPosting"> | number
  account_id?: Prisma.IntFilter<"JournalPosting"> | number
  debit?: Prisma.DecimalFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  journal?: Prisma.XOR<Prisma.JournalEntryScalarRelationFilter, Prisma.JournalEntryWhereInput>
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
}, "id">

export type JournalPostingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
  _count?: Prisma.JournalPostingCountOrderByAggregateInput
  _avg?: Prisma.JournalPostingAvgOrderByAggregateInput
  _max?: Prisma.JournalPostingMaxOrderByAggregateInput
  _min?: Prisma.JournalPostingMinOrderByAggregateInput
  _sum?: Prisma.JournalPostingSumOrderByAggregateInput
}

export type JournalPostingScalarWhereWithAggregatesInput = {
  AND?: Prisma.JournalPostingScalarWhereWithAggregatesInput | Prisma.JournalPostingScalarWhereWithAggregatesInput[]
  OR?: Prisma.JournalPostingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JournalPostingScalarWhereWithAggregatesInput | Prisma.JournalPostingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"JournalPosting"> | number
  journal_entry_id?: Prisma.IntWithAggregatesFilter<"JournalPosting"> | number
  account_id?: Prisma.IntWithAggregatesFilter<"JournalPosting"> | number
  debit?: Prisma.DecimalWithAggregatesFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalWithAggregatesFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingCreateInput = {
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  journal: Prisma.JournalEntryCreateNestedOneWithoutPostingsInput
  account: Prisma.AccountCreateNestedOneWithoutJournalPostingInput
}

export type JournalPostingUncheckedCreateInput = {
  id?: number
  journal_entry_id: number
  account_id: number
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUpdateInput = {
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  journal?: Prisma.JournalEntryUpdateOneRequiredWithoutPostingsNestedInput
  account?: Prisma.AccountUpdateOneRequiredWithoutJournalPostingNestedInput
}

export type JournalPostingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journal_entry_id?: Prisma.IntFieldUpdateOperationsInput | number
  account_id?: Prisma.IntFieldUpdateOperationsInput | number
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingCreateManyInput = {
  id?: number
  journal_entry_id: number
  account_id: number
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUpdateManyMutationInput = {
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journal_entry_id?: Prisma.IntFieldUpdateOperationsInput | number
  account_id?: Prisma.IntFieldUpdateOperationsInput | number
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingListRelationFilter = {
  every?: Prisma.JournalPostingWhereInput
  some?: Prisma.JournalPostingWhereInput
  none?: Prisma.JournalPostingWhereInput
}

export type JournalPostingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type JournalPostingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
}

export type JournalPostingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
}

export type JournalPostingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
}

export type JournalPostingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
}

export type JournalPostingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  journal_entry_id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  debit?: Prisma.SortOrder
  credit?: Prisma.SortOrder
}

export type JournalPostingCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutAccountInput, Prisma.JournalPostingUncheckedCreateWithoutAccountInput> | Prisma.JournalPostingCreateWithoutAccountInput[] | Prisma.JournalPostingUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutAccountInput | Prisma.JournalPostingCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.JournalPostingCreateManyAccountInputEnvelope
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
}

export type JournalPostingUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutAccountInput, Prisma.JournalPostingUncheckedCreateWithoutAccountInput> | Prisma.JournalPostingCreateWithoutAccountInput[] | Prisma.JournalPostingUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutAccountInput | Prisma.JournalPostingCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.JournalPostingCreateManyAccountInputEnvelope
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
}

export type JournalPostingUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutAccountInput, Prisma.JournalPostingUncheckedCreateWithoutAccountInput> | Prisma.JournalPostingCreateWithoutAccountInput[] | Prisma.JournalPostingUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutAccountInput | Prisma.JournalPostingCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.JournalPostingUpsertWithWhereUniqueWithoutAccountInput | Prisma.JournalPostingUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.JournalPostingCreateManyAccountInputEnvelope
  set?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  disconnect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  delete?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  update?: Prisma.JournalPostingUpdateWithWhereUniqueWithoutAccountInput | Prisma.JournalPostingUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.JournalPostingUpdateManyWithWhereWithoutAccountInput | Prisma.JournalPostingUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.JournalPostingScalarWhereInput | Prisma.JournalPostingScalarWhereInput[]
}

export type JournalPostingUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutAccountInput, Prisma.JournalPostingUncheckedCreateWithoutAccountInput> | Prisma.JournalPostingCreateWithoutAccountInput[] | Prisma.JournalPostingUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutAccountInput | Prisma.JournalPostingCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.JournalPostingUpsertWithWhereUniqueWithoutAccountInput | Prisma.JournalPostingUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.JournalPostingCreateManyAccountInputEnvelope
  set?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  disconnect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  delete?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  update?: Prisma.JournalPostingUpdateWithWhereUniqueWithoutAccountInput | Prisma.JournalPostingUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.JournalPostingUpdateManyWithWhereWithoutAccountInput | Prisma.JournalPostingUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.JournalPostingScalarWhereInput | Prisma.JournalPostingScalarWhereInput[]
}

export type JournalPostingCreateNestedManyWithoutJournalInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutJournalInput, Prisma.JournalPostingUncheckedCreateWithoutJournalInput> | Prisma.JournalPostingCreateWithoutJournalInput[] | Prisma.JournalPostingUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutJournalInput | Prisma.JournalPostingCreateOrConnectWithoutJournalInput[]
  createMany?: Prisma.JournalPostingCreateManyJournalInputEnvelope
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
}

export type JournalPostingUncheckedCreateNestedManyWithoutJournalInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutJournalInput, Prisma.JournalPostingUncheckedCreateWithoutJournalInput> | Prisma.JournalPostingCreateWithoutJournalInput[] | Prisma.JournalPostingUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutJournalInput | Prisma.JournalPostingCreateOrConnectWithoutJournalInput[]
  createMany?: Prisma.JournalPostingCreateManyJournalInputEnvelope
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
}

export type JournalPostingUpdateManyWithoutJournalNestedInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutJournalInput, Prisma.JournalPostingUncheckedCreateWithoutJournalInput> | Prisma.JournalPostingCreateWithoutJournalInput[] | Prisma.JournalPostingUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutJournalInput | Prisma.JournalPostingCreateOrConnectWithoutJournalInput[]
  upsert?: Prisma.JournalPostingUpsertWithWhereUniqueWithoutJournalInput | Prisma.JournalPostingUpsertWithWhereUniqueWithoutJournalInput[]
  createMany?: Prisma.JournalPostingCreateManyJournalInputEnvelope
  set?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  disconnect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  delete?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  update?: Prisma.JournalPostingUpdateWithWhereUniqueWithoutJournalInput | Prisma.JournalPostingUpdateWithWhereUniqueWithoutJournalInput[]
  updateMany?: Prisma.JournalPostingUpdateManyWithWhereWithoutJournalInput | Prisma.JournalPostingUpdateManyWithWhereWithoutJournalInput[]
  deleteMany?: Prisma.JournalPostingScalarWhereInput | Prisma.JournalPostingScalarWhereInput[]
}

export type JournalPostingUncheckedUpdateManyWithoutJournalNestedInput = {
  create?: Prisma.XOR<Prisma.JournalPostingCreateWithoutJournalInput, Prisma.JournalPostingUncheckedCreateWithoutJournalInput> | Prisma.JournalPostingCreateWithoutJournalInput[] | Prisma.JournalPostingUncheckedCreateWithoutJournalInput[]
  connectOrCreate?: Prisma.JournalPostingCreateOrConnectWithoutJournalInput | Prisma.JournalPostingCreateOrConnectWithoutJournalInput[]
  upsert?: Prisma.JournalPostingUpsertWithWhereUniqueWithoutJournalInput | Prisma.JournalPostingUpsertWithWhereUniqueWithoutJournalInput[]
  createMany?: Prisma.JournalPostingCreateManyJournalInputEnvelope
  set?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  disconnect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  delete?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  connect?: Prisma.JournalPostingWhereUniqueInput | Prisma.JournalPostingWhereUniqueInput[]
  update?: Prisma.JournalPostingUpdateWithWhereUniqueWithoutJournalInput | Prisma.JournalPostingUpdateWithWhereUniqueWithoutJournalInput[]
  updateMany?: Prisma.JournalPostingUpdateManyWithWhereWithoutJournalInput | Prisma.JournalPostingUpdateManyWithWhereWithoutJournalInput[]
  deleteMany?: Prisma.JournalPostingScalarWhereInput | Prisma.JournalPostingScalarWhereInput[]
}

export type JournalPostingCreateWithoutAccountInput = {
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  journal: Prisma.JournalEntryCreateNestedOneWithoutPostingsInput
}

export type JournalPostingUncheckedCreateWithoutAccountInput = {
  id?: number
  journal_entry_id: number
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingCreateOrConnectWithoutAccountInput = {
  where: Prisma.JournalPostingWhereUniqueInput
  create: Prisma.XOR<Prisma.JournalPostingCreateWithoutAccountInput, Prisma.JournalPostingUncheckedCreateWithoutAccountInput>
}

export type JournalPostingCreateManyAccountInputEnvelope = {
  data: Prisma.JournalPostingCreateManyAccountInput | Prisma.JournalPostingCreateManyAccountInput[]
  skipDuplicates?: boolean
}

export type JournalPostingUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.JournalPostingWhereUniqueInput
  update: Prisma.XOR<Prisma.JournalPostingUpdateWithoutAccountInput, Prisma.JournalPostingUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.JournalPostingCreateWithoutAccountInput, Prisma.JournalPostingUncheckedCreateWithoutAccountInput>
}

export type JournalPostingUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.JournalPostingWhereUniqueInput
  data: Prisma.XOR<Prisma.JournalPostingUpdateWithoutAccountInput, Prisma.JournalPostingUncheckedUpdateWithoutAccountInput>
}

export type JournalPostingUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.JournalPostingScalarWhereInput
  data: Prisma.XOR<Prisma.JournalPostingUpdateManyMutationInput, Prisma.JournalPostingUncheckedUpdateManyWithoutAccountInput>
}

export type JournalPostingScalarWhereInput = {
  AND?: Prisma.JournalPostingScalarWhereInput | Prisma.JournalPostingScalarWhereInput[]
  OR?: Prisma.JournalPostingScalarWhereInput[]
  NOT?: Prisma.JournalPostingScalarWhereInput | Prisma.JournalPostingScalarWhereInput[]
  id?: Prisma.IntFilter<"JournalPosting"> | number
  journal_entry_id?: Prisma.IntFilter<"JournalPosting"> | number
  account_id?: Prisma.IntFilter<"JournalPosting"> | number
  debit?: Prisma.DecimalFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFilter<"JournalPosting"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingCreateWithoutJournalInput = {
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  account: Prisma.AccountCreateNestedOneWithoutJournalPostingInput
}

export type JournalPostingUncheckedCreateWithoutJournalInput = {
  id?: number
  account_id: number
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingCreateOrConnectWithoutJournalInput = {
  where: Prisma.JournalPostingWhereUniqueInput
  create: Prisma.XOR<Prisma.JournalPostingCreateWithoutJournalInput, Prisma.JournalPostingUncheckedCreateWithoutJournalInput>
}

export type JournalPostingCreateManyJournalInputEnvelope = {
  data: Prisma.JournalPostingCreateManyJournalInput | Prisma.JournalPostingCreateManyJournalInput[]
  skipDuplicates?: boolean
}

export type JournalPostingUpsertWithWhereUniqueWithoutJournalInput = {
  where: Prisma.JournalPostingWhereUniqueInput
  update: Prisma.XOR<Prisma.JournalPostingUpdateWithoutJournalInput, Prisma.JournalPostingUncheckedUpdateWithoutJournalInput>
  create: Prisma.XOR<Prisma.JournalPostingCreateWithoutJournalInput, Prisma.JournalPostingUncheckedCreateWithoutJournalInput>
}

export type JournalPostingUpdateWithWhereUniqueWithoutJournalInput = {
  where: Prisma.JournalPostingWhereUniqueInput
  data: Prisma.XOR<Prisma.JournalPostingUpdateWithoutJournalInput, Prisma.JournalPostingUncheckedUpdateWithoutJournalInput>
}

export type JournalPostingUpdateManyWithWhereWithoutJournalInput = {
  where: Prisma.JournalPostingScalarWhereInput
  data: Prisma.XOR<Prisma.JournalPostingUpdateManyMutationInput, Prisma.JournalPostingUncheckedUpdateManyWithoutJournalInput>
}

export type JournalPostingCreateManyAccountInput = {
  id?: number
  journal_entry_id: number
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUpdateWithoutAccountInput = {
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  journal?: Prisma.JournalEntryUpdateOneRequiredWithoutPostingsNestedInput
}

export type JournalPostingUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journal_entry_id?: Prisma.IntFieldUpdateOperationsInput | number
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  journal_entry_id?: Prisma.IntFieldUpdateOperationsInput | number
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingCreateManyJournalInput = {
  id?: number
  account_id: number
  debit?: runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUpdateWithoutJournalInput = {
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  account?: Prisma.AccountUpdateOneRequiredWithoutJournalPostingNestedInput
}

export type JournalPostingUncheckedUpdateWithoutJournalInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  account_id?: Prisma.IntFieldUpdateOperationsInput | number
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type JournalPostingUncheckedUpdateManyWithoutJournalInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  account_id?: Prisma.IntFieldUpdateOperationsInput | number
  debit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  credit?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type JournalPostingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  journal_entry_id?: boolean
  account_id?: boolean
  debit?: boolean
  credit?: boolean
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["journalPosting"]>

export type JournalPostingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  journal_entry_id?: boolean
  account_id?: boolean
  debit?: boolean
  credit?: boolean
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["journalPosting"]>

export type JournalPostingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  journal_entry_id?: boolean
  account_id?: boolean
  debit?: boolean
  credit?: boolean
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["journalPosting"]>

export type JournalPostingSelectScalar = {
  id?: boolean
  journal_entry_id?: boolean
  account_id?: boolean
  debit?: boolean
  credit?: boolean
}

export type JournalPostingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "journal_entry_id" | "account_id" | "debit" | "credit", ExtArgs["result"]["journalPosting"]>
export type JournalPostingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}
export type JournalPostingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}
export type JournalPostingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  journal?: boolean | Prisma.JournalEntryDefaultArgs<ExtArgs>
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
}

export type $JournalPostingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JournalPosting"
  objects: {
    journal: Prisma.$JournalEntryPayload<ExtArgs>
    account: Prisma.$AccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    journal_entry_id: number
    account_id: number
    debit: runtime.Decimal
    credit: runtime.Decimal
  }, ExtArgs["result"]["journalPosting"]>
  composites: {}
}

export type JournalPostingGetPayload<S extends boolean | null | undefined | JournalPostingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload, S>

export type JournalPostingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JournalPostingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JournalPostingCountAggregateInputType | true
  }

export interface JournalPostingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JournalPosting'], meta: { name: 'JournalPosting' } }
  /**
   * Find zero or one JournalPosting that matches the filter.
   * @param {JournalPostingFindUniqueArgs} args - Arguments to find a JournalPosting
   * @example
   * // Get one JournalPosting
   * const journalPosting = await prisma.journalPosting.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JournalPostingFindUniqueArgs>(args: Prisma.SelectSubset<T, JournalPostingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JournalPosting that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JournalPostingFindUniqueOrThrowArgs} args - Arguments to find a JournalPosting
   * @example
   * // Get one JournalPosting
   * const journalPosting = await prisma.journalPosting.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JournalPostingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JournalPostingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JournalPosting that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingFindFirstArgs} args - Arguments to find a JournalPosting
   * @example
   * // Get one JournalPosting
   * const journalPosting = await prisma.journalPosting.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JournalPostingFindFirstArgs>(args?: Prisma.SelectSubset<T, JournalPostingFindFirstArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JournalPosting that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingFindFirstOrThrowArgs} args - Arguments to find a JournalPosting
   * @example
   * // Get one JournalPosting
   * const journalPosting = await prisma.journalPosting.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JournalPostingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JournalPostingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JournalPostings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JournalPostings
   * const journalPostings = await prisma.journalPosting.findMany()
   * 
   * // Get first 10 JournalPostings
   * const journalPostings = await prisma.journalPosting.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const journalPostingWithIdOnly = await prisma.journalPosting.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JournalPostingFindManyArgs>(args?: Prisma.SelectSubset<T, JournalPostingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JournalPosting.
   * @param {JournalPostingCreateArgs} args - Arguments to create a JournalPosting.
   * @example
   * // Create one JournalPosting
   * const JournalPosting = await prisma.journalPosting.create({
   *   data: {
   *     // ... data to create a JournalPosting
   *   }
   * })
   * 
   */
  create<T extends JournalPostingCreateArgs>(args: Prisma.SelectSubset<T, JournalPostingCreateArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JournalPostings.
   * @param {JournalPostingCreateManyArgs} args - Arguments to create many JournalPostings.
   * @example
   * // Create many JournalPostings
   * const journalPosting = await prisma.journalPosting.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JournalPostingCreateManyArgs>(args?: Prisma.SelectSubset<T, JournalPostingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JournalPostings and returns the data saved in the database.
   * @param {JournalPostingCreateManyAndReturnArgs} args - Arguments to create many JournalPostings.
   * @example
   * // Create many JournalPostings
   * const journalPosting = await prisma.journalPosting.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JournalPostings and only return the `id`
   * const journalPostingWithIdOnly = await prisma.journalPosting.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JournalPostingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JournalPostingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JournalPosting.
   * @param {JournalPostingDeleteArgs} args - Arguments to delete one JournalPosting.
   * @example
   * // Delete one JournalPosting
   * const JournalPosting = await prisma.journalPosting.delete({
   *   where: {
   *     // ... filter to delete one JournalPosting
   *   }
   * })
   * 
   */
  delete<T extends JournalPostingDeleteArgs>(args: Prisma.SelectSubset<T, JournalPostingDeleteArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JournalPosting.
   * @param {JournalPostingUpdateArgs} args - Arguments to update one JournalPosting.
   * @example
   * // Update one JournalPosting
   * const journalPosting = await prisma.journalPosting.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JournalPostingUpdateArgs>(args: Prisma.SelectSubset<T, JournalPostingUpdateArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JournalPostings.
   * @param {JournalPostingDeleteManyArgs} args - Arguments to filter JournalPostings to delete.
   * @example
   * // Delete a few JournalPostings
   * const { count } = await prisma.journalPosting.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JournalPostingDeleteManyArgs>(args?: Prisma.SelectSubset<T, JournalPostingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JournalPostings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JournalPostings
   * const journalPosting = await prisma.journalPosting.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JournalPostingUpdateManyArgs>(args: Prisma.SelectSubset<T, JournalPostingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JournalPostings and returns the data updated in the database.
   * @param {JournalPostingUpdateManyAndReturnArgs} args - Arguments to update many JournalPostings.
   * @example
   * // Update many JournalPostings
   * const journalPosting = await prisma.journalPosting.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JournalPostings and only return the `id`
   * const journalPostingWithIdOnly = await prisma.journalPosting.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JournalPostingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JournalPostingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JournalPosting.
   * @param {JournalPostingUpsertArgs} args - Arguments to update or create a JournalPosting.
   * @example
   * // Update or create a JournalPosting
   * const journalPosting = await prisma.journalPosting.upsert({
   *   create: {
   *     // ... data to create a JournalPosting
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JournalPosting we want to update
   *   }
   * })
   */
  upsert<T extends JournalPostingUpsertArgs>(args: Prisma.SelectSubset<T, JournalPostingUpsertArgs<ExtArgs>>): Prisma.Prisma__JournalPostingClient<runtime.Types.Result.GetResult<Prisma.$JournalPostingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JournalPostings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingCountArgs} args - Arguments to filter JournalPostings to count.
   * @example
   * // Count the number of JournalPostings
   * const count = await prisma.journalPosting.count({
   *   where: {
   *     // ... the filter for the JournalPostings we want to count
   *   }
   * })
  **/
  count<T extends JournalPostingCountArgs>(
    args?: Prisma.Subset<T, JournalPostingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JournalPostingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JournalPosting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JournalPostingAggregateArgs>(args: Prisma.Subset<T, JournalPostingAggregateArgs>): Prisma.PrismaPromise<GetJournalPostingAggregateType<T>>

  /**
   * Group by JournalPosting.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JournalPostingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JournalPostingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JournalPostingGroupByArgs['orderBy'] }
      : { orderBy?: JournalPostingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JournalPostingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJournalPostingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JournalPosting model
 */
readonly fields: JournalPostingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JournalPosting.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JournalPostingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  journal<T extends Prisma.JournalEntryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JournalEntryDefaultArgs<ExtArgs>>): Prisma.Prisma__JournalEntryClient<runtime.Types.Result.GetResult<Prisma.$JournalEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  account<T extends Prisma.AccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JournalPosting model
 */
export interface JournalPostingFieldRefs {
  readonly id: Prisma.FieldRef<"JournalPosting", 'Int'>
  readonly journal_entry_id: Prisma.FieldRef<"JournalPosting", 'Int'>
  readonly account_id: Prisma.FieldRef<"JournalPosting", 'Int'>
  readonly debit: Prisma.FieldRef<"JournalPosting", 'Decimal'>
  readonly credit: Prisma.FieldRef<"JournalPosting", 'Decimal'>
}
    

// Custom InputTypes
/**
 * JournalPosting findUnique
 */
export type JournalPostingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * Filter, which JournalPosting to fetch.
   */
  where: Prisma.JournalPostingWhereUniqueInput
}

/**
 * JournalPosting findUniqueOrThrow
 */
export type JournalPostingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * Filter, which JournalPosting to fetch.
   */
  where: Prisma.JournalPostingWhereUniqueInput
}

/**
 * JournalPosting findFirst
 */
export type JournalPostingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * Filter, which JournalPosting to fetch.
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalPostings to fetch.
   */
  orderBy?: Prisma.JournalPostingOrderByWithRelationInput | Prisma.JournalPostingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JournalPostings.
   */
  cursor?: Prisma.JournalPostingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalPostings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalPostings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JournalPostings.
   */
  distinct?: Prisma.JournalPostingScalarFieldEnum | Prisma.JournalPostingScalarFieldEnum[]
}

/**
 * JournalPosting findFirstOrThrow
 */
export type JournalPostingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * Filter, which JournalPosting to fetch.
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalPostings to fetch.
   */
  orderBy?: Prisma.JournalPostingOrderByWithRelationInput | Prisma.JournalPostingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JournalPostings.
   */
  cursor?: Prisma.JournalPostingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalPostings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalPostings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JournalPostings.
   */
  distinct?: Prisma.JournalPostingScalarFieldEnum | Prisma.JournalPostingScalarFieldEnum[]
}

/**
 * JournalPosting findMany
 */
export type JournalPostingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * Filter, which JournalPostings to fetch.
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JournalPostings to fetch.
   */
  orderBy?: Prisma.JournalPostingOrderByWithRelationInput | Prisma.JournalPostingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JournalPostings.
   */
  cursor?: Prisma.JournalPostingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JournalPostings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JournalPostings.
   */
  skip?: number
  distinct?: Prisma.JournalPostingScalarFieldEnum | Prisma.JournalPostingScalarFieldEnum[]
}

/**
 * JournalPosting create
 */
export type JournalPostingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * The data needed to create a JournalPosting.
   */
  data: Prisma.XOR<Prisma.JournalPostingCreateInput, Prisma.JournalPostingUncheckedCreateInput>
}

/**
 * JournalPosting createMany
 */
export type JournalPostingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JournalPostings.
   */
  data: Prisma.JournalPostingCreateManyInput | Prisma.JournalPostingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JournalPosting createManyAndReturn
 */
export type JournalPostingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * The data used to create many JournalPostings.
   */
  data: Prisma.JournalPostingCreateManyInput | Prisma.JournalPostingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * JournalPosting update
 */
export type JournalPostingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * The data needed to update a JournalPosting.
   */
  data: Prisma.XOR<Prisma.JournalPostingUpdateInput, Prisma.JournalPostingUncheckedUpdateInput>
  /**
   * Choose, which JournalPosting to update.
   */
  where: Prisma.JournalPostingWhereUniqueInput
}

/**
 * JournalPosting updateMany
 */
export type JournalPostingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JournalPostings.
   */
  data: Prisma.XOR<Prisma.JournalPostingUpdateManyMutationInput, Prisma.JournalPostingUncheckedUpdateManyInput>
  /**
   * Filter which JournalPostings to update
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * Limit how many JournalPostings to update.
   */
  limit?: number
}

/**
 * JournalPosting updateManyAndReturn
 */
export type JournalPostingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * The data used to update JournalPostings.
   */
  data: Prisma.XOR<Prisma.JournalPostingUpdateManyMutationInput, Prisma.JournalPostingUncheckedUpdateManyInput>
  /**
   * Filter which JournalPostings to update
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * Limit how many JournalPostings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * JournalPosting upsert
 */
export type JournalPostingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * The filter to search for the JournalPosting to update in case it exists.
   */
  where: Prisma.JournalPostingWhereUniqueInput
  /**
   * In case the JournalPosting found by the `where` argument doesn't exist, create a new JournalPosting with this data.
   */
  create: Prisma.XOR<Prisma.JournalPostingCreateInput, Prisma.JournalPostingUncheckedCreateInput>
  /**
   * In case the JournalPosting was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JournalPostingUpdateInput, Prisma.JournalPostingUncheckedUpdateInput>
}

/**
 * JournalPosting delete
 */
export type JournalPostingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
  /**
   * Filter which JournalPosting to delete.
   */
  where: Prisma.JournalPostingWhereUniqueInput
}

/**
 * JournalPosting deleteMany
 */
export type JournalPostingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JournalPostings to delete
   */
  where?: Prisma.JournalPostingWhereInput
  /**
   * Limit how many JournalPostings to delete.
   */
  limit?: number
}

/**
 * JournalPosting without action
 */
export type JournalPostingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalPosting
   */
  select?: Prisma.JournalPostingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalPosting
   */
  omit?: Prisma.JournalPostingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalPostingInclude<ExtArgs> | null
}
